// <auto-generated />
namespace AutoServiceManager.Common.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class InharitigPersons : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InharitigPersons));
        
        string IMigrationMetadata.Id
        {
            get { return "201404241743074_InharitigPersons"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
